### ISSUE TITLE
[Windows] - Color output gone in 1.1.0

### ISSUE THREAD

**Issue by twaileit** [composer/composer#5323]
Running composer --version on a Windows maschine, I get the following:
```
C:\>composer --version
←[32mComposer←[39m version ←[33m1.1.0←[39m 2016-05-10 15:21:19
```
This is just happening since the update to (I guess) 1.1.0.

**Comment by alcohol** [comment]
Looks more like an issue with your terminal not interpreting escape sequences properly.

**Comment by alcohol** [comment]
Please see if a `--rollback` resolves it.

**Comment by twaileit** [comment]
The thing is that npm works fine (I think it uses the same technique to provide colors?).

Rolled back to version 1.0-dev (7c62e2b5346a6a656dd9587203719e35bb768056) 2016-03-16 08:47:37 - at least the escape sequences for shells are not present anymore.

**Comment by gmsantos** [comment]
It's working fine here

![untitled](https://cloud.githubusercontent.com/assets/1991286/15265821/17354afc-1966-11e6-91ec-0f4e43d65d97.png)

**Comment by twaileit** [comment]
Very strange.

But I see, no big changes in the Output Class here, maybe I should open an issue in the symphony/console repo.

**Comment by foglcz** [comment]
I just encountered the same problem on my Windows 10 Insider Preview 2016/05/06

I don't have other (regular w10) build around to test it against, but everything is ok in win7

Which build of Win10 are you guys using?

**Comment by foglcz** [comment]
OK, seems like a problem with Windows 10 cmd.exe in preview builds. Also, it seems as something to be handled in symfony/console, as reported here -> https://github.com/symfony/symfony/issues/17499

**Comment by twaileit** [comment]
No preview build here, I am using Windows 10 Pro 1511 Build 10586.318 here.
Issue is not presens in an early 1.1.0 build of composer, but 1.2dev definitly has those issues.

**Comment by Seldaek** [comment]
This really needs to be dealt with in symfony/console as we are merely consuming it. I'll keep this open  for now as a reminder but please discuss details over there as much as possible.

**Comment by weierophinney** [comment]
It's not just Windows; I noticed this a few days back on Ubuntu. At first, it seemed to be only when in tmux, which reports as `TERM=screen` and/or `TERM=screen-256color`; however, on investigating it later today, I noticed it fails to render colors under `TERM=xterm-256color` (default under gnome-terminal) or `TERM=xterm` (the most common across terminal types in linux).

**Comment by kurkowskik** [comment]
@twaileit  In Windows you should right click on console window title and in options uncheck "Use legacy console (requires relaunch)". After console relaunch, everything is working fine with the newest composer version (1.1.1).

**Comment by twaileit** [comment]
@kurkowskik I was already using it, since the non-legacy version was broken in the days I switched to PHPStorm on Windows 10.

**Comment by alcohol** [comment]
@twaileit note that @kurkowskik wrote "uncheck", so specifically suggesting **not** to use it. :-)

**Comment by twaileit** [comment]
@alcohol guess I ignored the "un"check. shame on me :(

**Comment by mindplay-dk** [comment]
I'm using Git Bash on Win10 - output is borked here too.

![image](https://cloud.githubusercontent.com/assets/103348/15687546/a299d26c-2775-11e6-8dea-ffabc54bcbc3.png)

Legacy mode is **un**checked here.

**Comment by Mariyo** [comment]
Same with mine Git Bash on Win 10 as @mindplay-dk 

![image](https://cloud.githubusercontent.com/assets/1678254/15886064/22b7d814-2d5b-11e6-8b99-f75a8933c34a.png)

**Comment by njbarrett** [comment]
Same issue as @Mariyo and @mindplay-dk . Windows 10 Pro x64

![image](https://cloud.githubusercontent.com/assets/241407/16354597/9764b312-3acb-11e6-88e7-82accbe253a0.png)

**Comment by bckp** [comment]
Use powershell, as there it is still OK (even on Win 10 build 14393)

**Comment by Mariyo** [comment]
@bckp Same advice as "Use Linux or Mac"... 

Actually problem fixed with upgraded Git to 2.9+

**Comment by maryo** [comment]
I have Window 10 and I use the native command line but I have ANSICON installed. It works well. So probably because of that ANSICON though.

**Comment by dequeues** [comment]
Same issue. Not sure why they made this decision. Works in powershell bot not in native cmd.

**Comment by bgaillard** [comment]
I updated GIT to version 2.9.2 today and the problem is still their. @Mariyo did you just installed a new GIT version ? Did you change other configuration parameters ?

**Comment by alcohol** [comment]
@bgaillard he explicitly says he makes use of https://github.com/adoxa/ansicon

**Comment by bgaillard** [comment]
@alcohol ah ok did not saw this comment at first. Their are 2 different Mario* in the conversation :-), as you said @maryo uses ANSICON so it should explain why it works in his case. But the advice of @Mariyo (simply updgrading GIT) does now work (at least on my Windows 10 Pro 64 machine). Thanks

**Comment by alcohol** [comment]
@bgaillard oh drats, I totally overlooked that. My mistake :>

**Comment by bckp** [comment]
@Mariyo it is not advice, it is working workaround.

**Comment by Mariyo** [comment]
@bgaillard I unistalled old version and installed new GIT 2.9.2 My previous version was 1.9 I think (for sure less than v2)

**Comment by twaileit** [comment]
With Windows 10 Anniversary Update (1607, Build 14393.51), output in CMD is completely broken.

![Screenshot](https://cloud.githubusercontent.com/assets/7931987/17611056/1cf28ce6-6044-11e6-82b3-5ae9bf0ded42.PNG)

Using Ubuntu Bash (Beta) or Powershell "fixes" it.

**Comment by godfrey22** [comment]
@twaileit Same here, not only composer it seems all the other outputs that uses ANSI are broken as well.

**Comment by slsoft-slang** [comment]
Yeap! I concur, looks like last Windows 10 updates broke the ANSI output in CMD. Perfect timing to switch to powershell, farewell cmd.exe! (but it's still an annoying bug)

**Comment by Seldaek** [comment]
I hope you reported this to Microsoft as well and not just here because it
sure sounds like a bug over there.

**Comment by alcohol** [comment]
See symfony/symfony#19520

**Comment by cirdog** [comment]
If it hasn't been mentioned before, the global workaround for Windows is:

C:\ProgramData\ComposerSetup\bin\composer.bat

php "%~dp0composer.phar" %* --no-ansi

Adding the "--no-ansi" flag at the launch script of composer, then it eliminates the need to flag it for every command.

**Comment by lino10** [comment]
@cirdog hi, do you have a fix for laravel? it's not working for laravel artisan..

**Comment by shockgonewild** [comment]
@lino10   : you can also add --no-ansi to artisan commands  ;

`php artisan --no-ansi`

**Comment by lino10** [comment]
@shockgonewild Sorry, I meant the fix without inputting '--no-ansi' in every command.. Editing the composer.bat above is not working

**Comment by piksel** [comment]
@lino10 you can either make a cmd file containing:
`@php artisan --no-ansi %*`
and save it in your php directory as `artisan.cmd`
note that you'll have to emit `php` from your commands, i.e.: `artisan serve`
or if you DO want colors you can also just install [ANSICON](https://github.com/adoxa/ansicon) (using `ansicon.exe -i`)

**Comment by lino10** [comment]
@piksel Sorry for the late reply. Thanks, it's working 👍

**Comment by francoishill** [comment]
Thanks @piksel, `ansicon.exe -i` solved the issue.

Also note that [ConEmu](https://github.com/Maximus5/ConEmu) enables colors by default but only inside ConEmu application, not inside the "native" cmd.exe.

**Comment by nQben** [comment]
I find this a weird issue, this is in git bash, it can show colors, and then again it can't 
![image](https://cloud.githubusercontent.com/assets/3830366/22062654/1a3a9aca-dd7b-11e6-896c-ef2264541a03.png)

**Comment by stof** [comment]
the case where you have an issue is not in composer, so it is the wrong place to report it. Report it to the artisan mantainers

**Comment by mindplay-dk** [comment]
I did some digging - apparently Microsoft decided to disable ANSI support by default, it was previously enabled by default, but that changed with a Win 10 update at some point. Applications need to explicitly enable ANSI support, and it looks like current Windows builds of PHP [don't do that](https://bugs.php.net/bug.php?id=72768) yet.

**Comment by realvjy** [comment]
Downgrading Git from 2.11 to 2.10 solved my problem https://github.com/git-for-windows/git/releases/tag/v2.10.0.windows.1

**Comment by danielehrhardt** [comment]
Some Problem here.

**Comment by vferko** [comment]
Console colors seem to be an issue of newer Windows 10...
http://stackoverflow.com/q/44047988/985454

![image](https://cloud.githubusercontent.com/assets/2313018/26202882/52010a68-3bd9-11e7-96bd-162c171e3702.png)

**Comment by stof** [comment]
Composer does not output ANSI colors on Windows 10 anymore automatically, as it updated its symfony/console dependency to a version where the rules were updated to account for the changes in Windows 10 compared to the first insider preview versions.
But you have to make sure that your composer version is uptodate.

If you want to have colors on windows when using Composer, you will still need to use Ansicon or ConEmu for now, (which worked since years), until the day where PHP adds support for the Windows API enabling native support of colors (and composer is updated to use this new API).

**Comment by slsoft-slang** [comment]
Find your composer.bat file. Mine is at this location
C:\ProgramData\ComposerSetup\bin\


add --no-ansi to the launching command
@ECHO OFF php "%~dp0composer.phar " %* --no-ansi

-or-

switch to cygwin







---------------------------------------------
*Solutions Logisoft*

*Sébastien Lang*

*www.slsoft.ca <http://www.slsoft.ca>*

2017-05-18 9:16 GMT-04:00 Christophe Coevoet <notifications@github.com>:

**Comment by sinergycode** [comment]
Thanks a lot, i added in composer.bat next code: 
`php "%~dp0composer.phar" %* --no-ansi`
and it's working for 
`composer -v`
in console.

But for 
`laravel -v`
in console
is the same problem.
How to fix the problem?
