### ISSUE TITLE
[Idea] Add actuall php-version to composer.lock

### ISSUE THREAD

**Issue by heiglandreas** [composer/composer#5341]
Currently the ```composer.lock``` contains the ```platform```-entry that copies a value from the ```composer.json```s ```require```-section. (At least from what I've seen so far). 

But wouldn't it be more interesting to also add the *actual* PHP-Version under that the composer.lock was created? Why would that be interesting? I recently had the issue where a project was set up using PHP 5.4 (and the ```composer.lock``` was therefore locking libraries for that PHP-version). But I was trying to install that project using PHP 7. And therefore the libs locked in the ```composer.lock``` aren't available due to version-constraints. So even though the composer.lock is available it can not resolve to an installable project as the environment is different from the one used to lock those libs.

So in my eyes it would be a great idea to have 

* a possibility to see from looking at the ```composer.lock``` whether the environments would match
* a hint when calling ```composer install``` that the environment the lock-file was created with and my environment do not match
* composer fall back to ```composer update``` when the environments do not match.

At least having the first one would allow to create f.e. a badge ```composer.lock | php 5.6``` so one could easily see which version the lock file was created with.

All this is only relevant, when the ```composer.lock```-file is commited to the repository as is strongly suggested by different people (i.e. @rdohms). But then it is - in my eyes - vital to have a way of knowing which environment the file was created with.

**Comment by alcohol** [comment]
Platform requirements should be part of your "require" section in my humble opinion. If your target environment is 5.4, then developing on 7 should not allow you to use newer packages, cause you simply cannot use those on your target platform.

**Comment by heiglandreas** [comment]
That would then possibly leave you in an uninstallable state as it might not be possible to install the locked versions on a different PHP-version. See f.e phpunit which installs v4 on PHP5.5. So I create a composer.lock-file running PHP 5.5 that will include PHPUnit v4. When I then try to install those libraries using PHP 7 I will run into an uninstallable situation as PHPUnit will not install the v4-branch with PHP 7.

And just to make that clear, the idea is **not** to use it as a **platform requirement**, but as an **indication** of what version the composer.lock-file was written with.  The fallback-solution I refered to in the list would - in my eyes - be an optional goodie.

**Comment by alcohol** [comment]
I'm saying that platform requirements should be a part of your project requirements, which then removes the need for this "feature" request all together. It should not matter what version the lock file was generated on. Instead, everyone contributing to a project should know what it is intended to run on.

**Comment by heiglandreas** [comment]
The platform requirements might be ```"php" : "^5.3 || ^7.0"``` which does not allow to know which version a lib has been developed with. And even though the platform-requirement contains PHP 7.0 the person creating the ```composer.lock``` might be using PHP 5.5 and ensures that everything works out in PHP 7.0 by running tests on a CI-environment including PHP 7. In that case it might be interesting to know that the lock-file has been created with PHP 5.5.

**Comment by alcohol** [comment]
If that is your requirement, then all your dependencies should be able to satisfy those. Also it makes more sense then to explicitly set the platform version in your composer.json in that case so that local php versions use by developers don't influence the resolving process, which would/could result in slightly different lock files constantly. It's more about finding a proper work flow, rather than adjusting the tools to accommodate every possibly conceivable workflow. People are far too creative.

**Comment by heiglandreas** [comment]
It's not about constantly different lock files or whether dependencies are satisfied or not. The thing is, that **when** you commit your lock-file to the repository (which is higly debateable but favoured by some people) I need to know with which PHP-version this composer.lock-file was created. Especially as the lock-file contains the explicit commit of each requirement but the requirement of the PHP-Version is only contained with the entry from the composer.json-file.

This idea (it's an idea, not a feature-request or a requirement) is to ease knowledge of what PHP-Version is required to satisfy the specific versions locked in this file. When PHP is itself a requirement, it should also be treated like a requirement and the explicit version should be locked that was used.

Without that knowledge there is no reason to use the composer.lock for my development-process in libraries as I can not assure, that everyone is using the same PHP-Version and might run into issues using the composer.lock-file. And therefore there is no reason to commit the composer.lock-file. 

So **when** committing the composer.lock-file is encouraged there needs to be a way to know which PHP-version (also which availalbe extensions) it was created with. When this information is **not** available, there's no need to commit the composer lock file, as contributors will **have** to run ```composer update``` to get the libs that satisfy their PHP-versions.

**Comment by alcohol** [comment]
And once you have this information? Then what?

Like I said, by explicitly specifying a PHP version in the platform configuration (e.g. `composer config platform.php 5.4`) you remove the need for this as Composer will install the same dependencies on each developer environment regardless of what their actual local PHP version is.

**Comment by Seldaek** [comment]
- committing the lock file is not debatable IMO, it's just a good idea in 99% of cases.
- the transition to php7 is a bit unique and for sure some older packages won't work there, but blindly running updates is not a solution IMO
- if you add a platform config (https://getcomposer.org/doc/06-config.md#platform) the problem is fixed, and that's a good idea anyway..
- if it fails to install I assume it's telling you that package X is not compatible with php7 so that clearly tells you that the lock file wasn't made for php7 anyway. Adding more metadata won't fix this or give you any more relevant info I think.
- such metadata would mean the lock file keeps changing whenever someone runs an update with a different version or extension set, so the lock diffs would be even bigger than they are and especially contain a lot of unneeded changes.

So overall I don't think this feature is necessary nor valuable.

**Comment by heiglandreas** [comment]
I might have picked exactly those 1% where it wasn't a good idea to use the composer.lock file, and indeed, specifying a PHP-version using the ```platform```-key might fix the issue. But it still does not allow me to see what version the composer.lock file was created with.

And it's not only the transition to PHP 7 that might cause issues but libs or projects using different requirements for different versions. (like f.e. PHPUnit 4.8 supporting PHP 5.3 and PHPUnit 5.0 start support only for PHP 5.6. So no PHP 7 involved there)

The point might be that I have to run composer to see that the composer.lock-file is not suitable for my environment instead of being able to check beforehand that I might run into issues due to PHP-Version-mismatch issues. 

And the point that the lockfile would change more is not really a point, as it's already changing when someone runs an update. And as the php-version is already specified in the composer.lock it would mean updating that php-version-tag to the currently running PHP-Version. So not really that much more change.

But when @Seldaek thinks it's not suitable then that's OK for me.

**Comment by Seldaek** [comment]
I don't really see how going in a composer.lock and checking a bunch of versions is supposed to be easier than running composer install and it'll tell you if the versions don't match?!

**Comment by heiglandreas** [comment]
You would not need to check a bunch of versions but one (The PHP-Version). The easiest solution might be to extend composer to first check the composer.lock whether there's a version mismatch and display a message to the user whether that's ok or not. So *fail fast* without having to check version constraints of the actual dependencies.

Or one could f.e. create a badge, that checks for that value and displays it in the README. Or display that information in packagist.org. That's just to name a few.

**Comment by Seldaek** [comment]
Yeah I don't get why it's a problem though, it's in most cases not a 
problem, so displaying a warning every time even though it actually is 
not a problem would cause more problems than it fixes.

In those few cases where there is an actual version conflict, then it 
will give you a solving conflict usually within a few milliseconds if 
it's installing from a lock file, so that's "fail fast" enough IMO, and 
most importantly "fail correctly".

**Comment by heiglandreas** [comment]
I never said it's a problem. It was an idea to make things easier for users. I stumbled over it while creating a badge whether or not a project commited their .lock-file to the repo and while doing that I came across the mentioned version-contraints that brought me to the idea that it would be an idea to be able to retrieve the PHP-Version the lock-file was created with from the file to be able to create a badge.

So I don't have a problem with the current state. It was just an idea!
