### ISSUE TITLE
Composer dump-autoload with repository path

### ISSUE THREAD

**Issue by 7elix** [composer/composer#5520]
With the following composer.json:

```json
{
    "repositories": {
        {
            "type": "path",
            "url": "local-folder/local-composer-package"
        },
    }
}
```

With recent changes in local-folder/local-composer-package/composer.json concerning autoload section with classmap.

When I run this command:

`composer update`
or
`composer dump-autoload`

I assume new autoload configuration is read and put into vendor/composer/autoload_classmap.php

But the changes from local-folder/local-composer-package/composer.json are not re-read and put into project autoload configuration.

Only removal of target symlink and composer update brings new classmap autoload php file.

**Comment by alcohol** [comment]
Your composer.json example is invalid. But I will assume you actually have a working valid composer.json on your local environment.

As far as I know, changes in autoload definitions should be detected immediately.

**Comment by 7elix** [comment]
Thanks for your feedback!!

Me composer files were valid and validated.
I created a git repository with demo bash script in order to easily review the issue.

Feel free to clone

- `git clone https://github.com/7elix/5520-composer`
- run `./demo-change-folder.sh `

and observe that the psr4-autoloading file did not change.
Neither with composer dump-autoload not with composer update.

Hope that there is no problem with composer Repository within composer based project.

Thanks you very much for helping me out here!
Much appreciated.

**Comment by alcohol** [comment]
Your example scenario is wrong. Your requirement refers to a specific version. Change it to "*" instead, or "dev-master".

**Comment by alcohol** [comment]
After fixing the various issues with your example scenario, I

* ran a `composer install`
* modified psr4 definition
* ran a `composer update phorax/demo-package`

and the result was as expected, the psr4 autoload file was updated.

**Comment by 7elix** [comment]
Thank you very much.
I updated the Repository according to your hints:

- Root composer json now required */dev-master (https://github.com/7elix/5520-composer/commit/b316349286ae0155a64c36b7b8a62b17bcd5f9b6)
- Changes repositories definition to Array (https://github.com/7elix/5520-composer/commit/db0fe9032a14cb93b066c0c2970c9a7549147c18)
- Fixed the repositories path for case-sensitive file systems (https://github.com/7elix/5520-composer/commit/61f27d4444311739531e77930ab7887576d7fe8a)
- Removed the local version number within package (https://github.com/7elix/5520-composer/commit/b54bd2e4f9dc2410a294045e0c1ba8bcbbd15a25)

That version is tagged with comment-4 git tag.


Alright, now to me expectation:

### Situation
That setup with root composer json and local Repository with path definition is set up. `Composer validate` does not find any errors and `composer install` creates the local symlink within vendor/phorax/demo-package as expected. `composer update` does not find any updates thus composer.lock is not changed. All fine. 

### Action
Now changes within package happen: e.g. "Classes/" sub-directory is moved to "src/" and the package composer.json file is adapted accordingly.

Commands:
- `mv "Repository/demo-package/Classes/" "Repository/demo-package/src/"`
- `sed -i.bak "s/Classes/src/g" "Repository/demo-package/composer.json"`

At his point the composer package has been changed and new autoloading information is present that were not yet registered in the project / root composer. In order to transport these changes from the composer package into the root composer:

- I run `composer update` on project root but the autoload changes are not registered in `vendor/composer/autoload_psr4.php`
- I run `composer update phorax/demo-package` on project root but the autoload files are still not updates to reflect the new src path
- Also `composer dump-autoload` on project root does not re-create the autoload files to reflect the new src path

The line 
`'Phorax\\DemoPackage\\' => array($vendorDir . '/phorax/demo-package/Classes')`

is not changed into
`'Phorax\\DemoPackage\\' => array($vendorDir . '/phorax/demo-package/src')`

### Work-around
By removing the vendor directory and running `composer install` the autoload files are re-written based on the current package composer.json file.

THANKS for your time and support! 🌞

**Comment by 7elix** [comment]
Also the composer info is not updates yet:

➜ ~/Sites/5520-composer (master) `composer info phorax/demo-package`
```
name     : phorax/demo-package
descrip. : Demo pachage in sub-directory
keywords : 
versions : * 1.2.3
type     : library
license  : GPL2+
source   : []  
dist     : [path] repository/demo-package aa61c1251f805436bc062ab582ca9bff0a39d0e7
names    : phorax/demo-package

autoload
psr-4
Phorax\DemoPackage\ => Classes/
```


to display `src/` as PSR-4 autoload directory.

**Comment by alcohol** [comment]
You still have a few issues in your example repo:

* require dev-master instead of *, or allow minimum-stability "dev"
* remove the .lock file (it contains invalid data which confuses composer)
* your .sh script does not do a composer update after modifying the composer.json of the subpackage

If you remove the lock file and apply the following patch, everything works as expected.

``` patch
diff --git i/composer.json w/composer.json
index ca3bf7a..c018f87 100644
--- i/composer.json
+++ w/composer.json
@@ -15,6 +15,6 @@
         }
     ],
     "require": {
-        "phorax/demo-package": "*"
+        "phorax/demo-package": "dev-master"
     }
 }
diff --git i/demo-change-folder.sh w/demo-change-folder.sh
index b4b12fe..a79e20c 100755
--- i/demo-change-folder.sh
+++ w/demo-change-folder.sh
@@ -14,16 +14,13 @@ then
        echo "Replacing autoload section in package composer.json"
        sed -i.bak "s/Classes/src/g" "Repository/demo-package/composer.json"
 
-       echo "Running composer dump-autoload (no-change)"
-       composer dump-autoload
+       echo "Running composer update"
+       composer update
 
        echo "PSR-4 autoload *after"
        cat "vendor/composer/autoload_psr4.php"
 
-       echo "Running composer upload (no-change)"
-       composer dump-autoload
-
        echo "PSR-4 autoload *after"
        cat "vendor/composer/autoload_psr4.php"
 
-fi
\ No newline at end of file
+fi
```

**Comment by 7elix** [comment]
Thanks! 

I have set the composer package requirement to "`dev-master`" instead of "`*`" and now the "`composer update`" command also updates the autoload-information.

### Summary

- do not use package version number in composer.json with repository type path
- require package version "`dev-master`" even with repository type path and without vcs

I updated the code in case anyone else stumbles upon this.

-> Thank you very much!
Please post the link to your amazon wishlist!

**Comment by alcohol** [comment]
I don't actually have an amazon wishlist... but @Seldaek does. You can find a link to it [here](https://seld.be/about). Considering all the work and time he has put into Composer, he probably deserves it more than me anyway :p
