### ISSUE TITLE
"which <packagename>" Doesnt work on packages installed via composer.

### ISSUE THREAD

**Issue by damngamerz** [composer/composer#6181]
`which <packagename>`when invoked in CLI returns the path where the package is installed.
Suppose
```
which composer
/usr/local/bin/composer
```
whereas if the package is installed by composer,and is invoked through `which` it returns nothing.
I have tried this for 2 or more packages through composer.
For a Detailed Description follow this:
https://github.com/coala/coala-bears/issues/1426

**Comment by alcohol** [comment]
`which` depends on `PATH` being setup properly. Composer has nothing to do with this.

**Comment by damngamerz** [comment]
@alcohol 
For every installed package, we can run it through the cli by its name, but `which <packagename>` returns nothing for packages installed via composer(As I said I have already tried this for 1 or more packages being installed via composer).This is related to composer.
And Im working on a tool, which uses `which <packagename>` to determine what is installed.So i can't do the followup task if i dont find a solution to this.See these screenshots.
![screenshot from 2017-02-17 18-25-27](https://cloud.githubusercontent.com/assets/13048113/23077879/4bb22a92-f56c-11e6-8041-170a39d1db65.png)
![screenshot from 2017-02-20 21-03-11](https://cloud.githubusercontent.com/assets/13048113/23131457/0607de7e-f7b0-11e6-8628-b8dc7c8bb3a4.png)
For more details about commands which i have used follow https://github.com/coala/coala-bears/issues/1426
I have installed a package named `phpstan` globally via composer and added it to `PATH`now invoking `which phpstan` in cli returns nothing whereas `whereis phpstan` returns the required intended behaviour, confirming that the `PATH` is well set.

**Comment by stof** [comment]
which is not about checking what is installed on the system. ``which <executable>`` is about showing you how ``<executable>`` is resolved using the PATH, to see what will be executed when calling the executable. 
and for me, ``which <executable>`` works fine for executables  installed by composer.

and btw, ``whereis phpstan`` does **not** find PHPStan either above. The list it gives you is empty. Here is how the ``whereis`` output looks like when it finds something:

```
whereis phpunit
phpunit: /usr/local/bin/phpunit /home/stof/src/Incenteev/TranslationCheckerBundle/vendor/bin/phpunit
```

**Comment by SanketDG** [comment]
@stof

But what would cause composer packages to not have a `which` entry yet being able to call by his name?

Because even when a program gets called by its name, its gets searched in the path, and `which` displays this path, so this is erratic behaviour.

Thoughts?

**Comment by stof** [comment]
do you have some bash alias which could be the one being called instead ?

**Comment by damngamerz** [comment]
@stof Oh I see! hmmm..
Tried adding `alias phpstan='~/.config/composer/vendor/bin/phpstan'` to `~/.bashrc` 
still not working.Tell me if Im doing something wrong.
![screenshot from 2017-02-21 02-04-00](https://cloud.githubusercontent.com/assets/13048113/23140910/1ec6f628-f7da-11e6-91a9-55a79888a9d1.png)

**Comment by stof** [comment]
adding an alias will not make it work for ``which`` or ``whereis``.

Can you display the path ? ``echo $PATH``

**Comment by damngamerz** [comment]
@stof Here
```
damngamerz@sauravsingh:~$ echo $PATH
/home/damngamerz/anaconda3/bin:/home/damngamerz/bin:/home/damngamerz/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/java/jre1.8.0_111/bin:/usr/local/java/jdk1.8.0_111/bin
```
