### ISSUE TITLE
Set preferred-install for specific packages from command line

### ISSUE THREAD

**Issue by jonathanjfshaw** [composer/composer#6301]
It doesn't seem possible to set  a global config preferred-install for specific packages from the command line.

I'm trying to setup containers for contributing to Drupal, using a third-party composer.json from drupal-composer/drupal-project. I'd like all drupal packages to be downloaded prefer-source, but all upstream dependencies to be prefer-dist.

However, from the cli this sort of thing does not seem possible:
`composer config --global preferred-install '{"drupal/*":"source"}'`

**Comment by alcohol** [comment]
The `composer config` command is somewhat of a glued together bundle of spaghetti. It could very well be the case that this particular config attribute has not been added yet to the list of cases that the command can handle.

From what I can tell by just quickly looking at the source code, it only accepts values on a global level, not on a vendor/package level: https://github.com/composer/composer/blob/master/src/Composer/Command/ConfigCommand.php#L300-L307

Pull requests are welcome.

**Comment by smoqadam** [comment]
Hi

I'm a new contributer and want to help. I want to grab this one but have no idea what to do? 

If this issue is not good for start please introduce me something else

**Comment by lf-jeremy** [comment]
It is worth noting that in the meantime, this can be accomplished via config as an alternative option that might be acceptable in some use cases:

https://getcomposer.org/doc/06-config.md#preferred-install

That support was added by https://github.com/composer/composer/pull/3790 should anyone want to see related work for implementing this for cli.

It seems a cli option will involve the nuances of how explicit cli options may interact with config-based options that are inherited.

**Comment by alcohol** [comment]
@smoqadam it depends on your familiarity with php I suppose.

Basically, the config command can be used to modify the config section of the `composer.json` file from the command line interface.

This is the command in question: [ConfigCommand](https://github.com/composer/composer/blob/master/src/Composer/Command/ConfigCommand.php)

If you read through the `execute()` method you should be able to get a gist of how it handles the input it receives. The `preferred-install` config section is currently handled here: https://github.com/composer/composer/blob/3c173702b5e45ba8180f991744ef947e863ece28/src/Composer/Command/ConfigCommand.php#L305-L312

Perhaps it would suffice to simply treat it as a multi-value setting, similar to these: https://github.com/composer/composer/blob/3c173702b5e45ba8180f991744ef947e863ece28/src/Composer/Command/ConfigCommand.php#L412-L455

**Comment by adrianosferreira** [comment]
@alcohol I've jumped here, I hope it is OK. Can you check it once you get some time, please? https://github.com/composer/composer/pull/8517

**Comment by Seldaek** [comment]
Fixed by #8517 - usable as `composer config preferred-install.foo/bar dist` for example.

**Comment by sergeynezbritskiy** [comment]
@Seldaek Any idea when 1.10 will be released ? Looking forward to this feature.

**Comment by Seldaek** [comment]
You can use snapshots for now `composer self-update --snapshot`, but I'll try to release soon.

**Comment by sergeynezbritskiy** [comment]
Hi @Seldaek thank you for your response so fast! I used snapshot and got this working,
but when I try to set it globally, like `composer global config "preferred-install.sergeynezbritskiy/*" source`, this config is pushed to $COMPOSER_HOME/composer.json, but expected to be pushed to $COMPOSER_HOME/config.json.
So if I want to set this configuration globally I still can't use `composer global config` command and need to edit global config.json manually
Any suggestions ?

**Comment by sergeynezbritskiy** [comment]
Oh, sorry
`composer config --global  "preferred-install.sergeynezbritskiy/*" source`
this command works fine, configuration is pushed to config.json in $COMPOSER_HOME
Waiting for official release then
@adrianosferreira @Seldaek thanks a lot !

**Comment by alcohol** [comment]
`composer global config` and `composer config --global` don't do the same thing, which I understand can be confusing :sweat_smile:

**Comment by jrfnl** [comment]
I was just looking to see if something like this could be done. Very happy to see this has been implemented, fits the bills for what I needed perfectly! :heart:

**Comment by jrfnl** [comment]
And... had to go look for this again as I couldn't figure out the syntax, only to see my own comment above.

Might it be an idea to add some CLI examples, like per https://github.com/composer/composer/issues/6301#issuecomment-573774392 to the https://getcomposer.org/doc/06-config.md page ?
