### ISSUE TITLE
i can't install my package to my project using composer.

### ISSUE THREAD

**Issue by mygituser12** [composer/composer#7603]
My `composer.json`:

```json
{
    "name": "coinremitphp/coin-remitter",
    "description": "coin remitter sdk for php",
    "type": "library",
    "keywords": ["coinremitter", "php", "cryptocurrency", "payment gateway", "api"],
    "homepage": "https://coinremitter.com/",
    "license": "MIT",
    
    "authors": [
        {
            "name": "name",
            "email": "your@name.com"
        }
    ],

   
    "require": {
        "php": ">=5.3.0"
    },
    "require-dev": {
        "php": ">=5.3.0"
    },
    "autoload": {
        "psr-0": {
            "CoinRemitter": "src/"
        }
    },
    "extra": {
        "branch-alias": {
            "dev-master": "0.1-dev"
        }
    }

}
```

When I run this command:

```
composer require coinremitphp/coin-remitter
```

I get the following output:

```
 [InvalidArgumentException]                                                                                                                                  
  Could not find package coinremitphp/coin-remitter at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
```

And I expected this to happen:the package should be install in project.

**Comment by oxycoder** [comment]
same problem here.
Couldn't install my package.

**Comment by saleem-hadad** [comment]
same here

**Comment by JMeyer81** [comment]
Also having a similar problem... Packagist says my package has been updated/uploaded; however after almost 24 hours I still can't install updates with Composer...

**Comment by saleem-hadad** [comment]
I've submitted my package and linked it correctly with Github. I've added a new release still can't install it 🚶 
https://packagist.org/packages/saleem-hadad/larecipe

**Comment by alcohol** [comment]
Cannot reproduce;

```
rob@galaga ~ $ cd /tmp
rob@galaga /tmp $ composer require coinremitphp/coin-remitter
Using version ^0.1.0 for coinremitphp/coin-remitter
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing coinremitphp/coin-remitter (0.1): Downloading (100%)         
Writing lock file
Generating autoload files
```

**Comment by oxycoder** [comment]
From this package: https://packagist.org/packages/oxycoder/laravel-apidoc-generator
It show 2.1.2 is latest version, but composer can't find any version 2.1.2.
The latest version composer can install is 2.1.1.

**Comment by xabbuh** [comment]
I cannot reproduce:

```
$ composer require oxycoder/laravel-apidoc-generator
Using version ^2.1 for oxycoder/laravel-apidoc-generator
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 37 installs, 0 updates, 0 removals
  - Installing vlucas/phpdotenv (v2.5.1): Loading from cache
  - Installing symfony/css-selector (v4.1.4): Loading from cache
  - Installing tijsverkoyen/css-to-inline-styles (2.2.1): Downloading (100%)         
  - Installing symfony/polyfill-php72 (v1.9.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.9.0): Loading from cache
  - Installing symfony/var-dumper (v4.1.4): Downloading (100%)         
  - Installing symfony/routing (v4.1.4): Downloading (100%)         
  - Installing symfony/process (v4.1.4): Downloading (100%)         
  - Installing symfony/polyfill-ctype (v1.9.0): Loading from cache
  - Installing symfony/http-foundation (v4.1.4): Downloading (100%)         
  - Installing symfony/event-dispatcher (v4.1.4): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v4.1.4): Downloading (100%)         
  - Installing symfony/http-kernel (v4.1.4): Downloading (100%)         
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing symfony/finder (v4.1.4): Loading from cache
  - Installing symfony/console (v4.1.4): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing egulias/email-validator (2.1.5): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.1.2): Loading from cache
  - Installing ramsey/uuid (3.8.0): Loading from cache
  - Installing psr/simple-cache (1.0.1): Downloading (100%)         
  - Installing psr/container (1.0.0): Downloading (100%)         
  - Installing symfony/translation (v4.1.4): Loading from cache
  - Installing nesbot/carbon (1.25.0): Downloading (100%)         
  - Installing monolog/monolog (1.23.0): Loading from cache
  - Installing league/flysystem (1.0.46): Downloading (100%)         
  - Installing erusev/parsedown (1.7.1): Loading from cache
  - Installing dragonmantank/cron-expression (v2.2.0): Downloading (100%)         
  - Installing doctrine/inflector (v1.3.0): Loading from cache
  - Installing laravel/framework (v5.6.37): Downloading (100%)         
  - Installing php-di/invoker (2.0.0): Downloading (100%)         
  - Installing mnapoli/silly (1.7.0): Downloading (100%)         
  - Installing symfony/yaml (v4.1.4): Downloading (100%)         
  - Installing mnapoli/front-yaml (1.6.0): Downloading (100%)         
  - Installing fzaninotto/faker (v1.8.0): Downloading (100%)         
  - Installing oxycoder/laravel-apidoc-generator (2.1.2): Downloading (100%)         
symfony/routing suggests installing doctrine/annotations (For using the annotation loader)
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/dependency-injection (For loading routes from a service)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/browser-kit ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/console suggests installing symfony/lock ()
swiftmailer/swiftmailer suggests installing true/punycode (Needed to support internationalized email addresses, if ext-intl is not installed)
ramsey/uuid suggests installing ircmaxell/random-lib (Provides RandomLib for use with the RandomLibAdapter)
ramsey/uuid suggests installing ext-libsodium (Provides the PECL libsodium extension for use with the SodiumRandomGenerator)
ramsey/uuid suggests installing ext-uuid (Provides the PECL UUID extension for use with the PeclUuidTimeGenerator and PeclUuidRandomGenerator)
ramsey/uuid suggests installing moontoast/math (Provides support for converting UUID to 128-bit integer (in string form).)
ramsey/uuid suggests installing ramsey/uuid-doctrine (Allows the use of Ramsey\Uuid\Uuid as Doctrine field type.)
ramsey/uuid suggests installing ramsey/uuid-console (A console application for generating UUIDs with ramsey/uuid)
symfony/translation suggests installing symfony/config ()
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with AWS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with AWS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob storage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator for metadata caching)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use EventableFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud Files)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage via phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapter)
league/flysystem suggests installing spatie/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing srmklive/flysystem-dropbox-v2 (Allows you to use Dropbox storage for PHP 5 applications)
laravel/framework suggests installing aws/aws-sdk-php (Required to use the SQS queue driver and SES mail driver (~3.0).)
laravel/framework suggests installing doctrine/dbal (Required to rename columns and drop SQLite columns (~2.6).)
laravel/framework suggests installing guzzlehttp/guzzle (Required to use the Mailgun and Mandrill mail drivers and the ping methods on schedules (~6.0).)
laravel/framework suggests installing laravel/tinker (Required to use the tinker console command (~1.0).)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
laravel/framework suggests installing league/flysystem-cached-adapter (Required to use the Flysystem cache (~1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
laravel/framework suggests installing league/flysystem-sftp (Required to use the Flysystem SFTP driver (~1.0).)
laravel/framework suggests installing nexmo/client (Required to use the Nexmo transport (~1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drivers (~1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast driver (~3.0).)
laravel/framework suggests installing symfony/dom-crawler (Required to use most of the crawler integration testing tools (~4.0).)
laravel/framework suggests installing symfony/psr-http-message-bridge (Required to psr7 bridging features (~1.0).)
Writing lock file
Generating autoload files
```

Maybe some other constraints prevent the newer release from being installed for you.

**Comment by inc2734** [comment]
My library can `composer install` on Travis CI, but it can not be installed on my computer. In addition, packagist 's api can correctly obtain the latest version information. Location problems?

**Comment by tkc49** [comment]
Same Problem.
`composer require tkc49/kintone-sdk-for-wordpress`

```
  [InvalidArgumentException]
  Could not find a version of package tkc49/kintone-sdk-for-wordpress matchin
  g your minimum-stability (stable). Require it with an explicit version cons
  traint allowing its desired stabilit
```

**Comment by oxycoder** [comment]
Yeah, I think this is region problem.
Create new virtual machine run
```
composer require oxycoder/laravel-apidoc-generator
```
Still give me version 2.1.1 instead of 2.1.2

"dev-master" point to b00d230 (2.1.1), not the latest commit 587fba9 (2.1.2)

**Comment by Seldaek** [comment]
If you still experience an issue here please tell me what file/package you're having issues with and which IP repo.packagist.org resolves to.

**Comment by tkc49** [comment]
Thank you very much!
It works!!!! 👍

**Comment by tanakahisateru** [comment]
`lapaz/codeception-psr15` still not.

```
$ nslookup repo.packagist.org
Server:		172.20.10.1
Address:	172.20.10.1#53

Non-authoritative answer:
Name:	repo.packagist.org
Address: 139.99.121.122
```

**Comment by tanakahisateru** [comment]
@Seldaek Also `lapaz/odango` now.

**Comment by Seldaek** [comment]
@tanakahisateru should be back now.. it got stuck again, not sure what's going on, I'll have to investigate further if it keeps happening.

**Comment by tanakahisateru** [comment]
@Seldaek latest versions are visible now. I'll try to update minor versions of them later.

**Comment by koriym** [comment]
@Seldaek `bear/resource` is having the issue with this IP.

```
AkiMac:BEAR.ApiDoc akihito$ nslookup repo.packagist.org
Server:		10.0.1.1
Address:	10.0.1.1#53

Non-authoritative answer:
Name:	repo.packagist.org
Address: 139.99.121.122
```

**Comment by Seldaek** [comment]
@koriym fixed now and I added some monitoring to it so it should auto-fix it from now on if it gets stuck.

**Comment by koriym** [comment]
@Seldaek Confirmed! Thank you for fixing quickly.

**Comment by koriym** [comment]
@Seldaek Which action should I take first if I find the server not running properly? (Do you have a server status page? or raise an issue like here?)

**Comment by Seldaek** [comment]
Please notify here if it gets stuck again but I hope the monitoring will be good enough.

**Comment by GaneshKandu** [comment]
@Seldaek i am still getting same issue
``php composer.phar create-project grumpydictator/firefly-iii --no-dev --prefer-dist firefly4761 4.7.6.1``

**Comment by csmtcy** [comment]
Hi @Seldaek i get the same problem for `vvinners/messenger`

```
Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
Name:    repo.packagist.org
Addresses:  2402:1f00:8002:100::91a
          139.99.121.122
```

**Comment by Seldaek** [comment]
@csmtcy This has been resolved, we had an issue with the metadata mirroring over the weekend sorry about that.

**Comment by Doqnach** [comment]
@Seldaek how about `psr/log-implementation`? Having issues requiring this meta-package right now.

```
Name:      repo.packagist.org
Address 1: 54.37.4.73 ip-54-37-4.eu
Address 2: 2001:41d0:401:2100::6bd
```

**Comment by tmdan** [comment]
@Seldaek Hi. Got same issuewith package -  tmdan/laravel-api-logger.  Please help.

**Comment by Seldaek** [comment]
@tmdan I added a warning now explaining what is going on, see [your package page](https://packagist.org/packages/tmdan/laravel-api-logger), let me know if this isn't clear enough.

**Comment by tmdan** [comment]
> I added a warning now explaining what is going on, see [your package page](https://packagist.org/packages/tmdan/laravel-api-logger), let me know if this isn't clear enough.
Thanks for support, it's  clear, there is a need to update Composer to version 2

**Comment by airdev-web** [comment]
Hi @Seldaek, greetings from Belgium!

I have also an issue with my package ``airdev/contact``. 

When I require my package :
```shell
composer require airdev/contact
```
I have the following issue :
```shell
Package airdev/contact not found in /httpdocs/composer.json
```

By the way, it's working on my local machine, but I got this error when I'm using it on my VPS ``composer v.2.1.3``.

Thanks for help 🙏
