### ISSUE TITLE
Unable to override composer/installers due to plugin loading order.

### ISSUE THREAD

**Issue by roygoldman** [composer/composer#8320]
My `composer.json`:

```json
{
    "name": "example/drupal-project",
    "description": "Composer installers error demo",
    "type": "project",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "license": "GPL-2.0-only",
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ],
    "require": {
        "roygoldman/drupal-project-installers": "^8.0",
        "roygoldman/composer-installers-discovery": "^1.0",
        "roygoldman/composer-where": "^1.0",
        "drupal/core": "^8.7",
        "drupal/webform": "^5.0",
        "composer/installers": "^1.2.0"
    }
}
```

Output of `composer diagnose`:
```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (1.8.0 => 1.9.0)
Composer version: 1.8.0
PHP version: 7.3.7
PHP binary path: /usr/bin/php7.3
```

When I run this command:

```
composer install && composer where drupal/webform
```

I get the following output:

```
drupal/webform(type:drupal-module managed by Composer\Installers\Installer) is installed at /home/reg98/drupal_sites/wifi/modules/webform
```
Due to the sorting of composer packages during plugin loading, the composer plugins get loaded in reverse alphabetical order. As a result, the `roygoldman/drupal-project-installers` which leverages `roygoldman/composer-installers-discovery` to determine the installation path of the drupal modules, so that they don't have to be tracked in each project's composer.json breaks. This is the result of the installer being part of  `roygoldman/composer-installers-discovery`  which gets loaded prior to `composer/installers`, at which point the generic installer takes priority over the custom installer. The sorting in question was added in relation to #8065. A similar race condition is what is happening here. 

While this issue was discovered doing something that may be uncommon this issue is likely present when loading any project which includes an installer mean to override `composer/installers`. In my use case, `composer/installers` isn't required by my root project but by another dependency, so it's inclusion is unavoidable, and I need to work around this.

Based on my testing, it appears this is the result of composer only partially rebuilding the dependecy in  "PluginManager::loadRepository" resulting in a case where this doesn't load the full project's `composer.json` and only some of the packages. For example, in a test project with 167 dependencies, `loadRepository` is called multiple times with a different number of repos each time (167, 43, 30, 22).

It appears to me that what's happening is that the plugins for dependencies are being loaded after their dependents, which is unclear, since you would expect the reverse order to happen, as this would mean that if a plugin has init code which should run after its dependency, then that isn't happening due to the load order. Additionally, for my use case, since the plugins initialize installers at run time, its impossible to override the installer of a dependency. To me this works as expected by removing the `array_reverse` call, but it may break the desired functionality and cause a regression of the fix in #8085.

**Comment by Seldaek** [comment]
I *think* the problem is roygoldman/composer-installers-discovery does not require composer/installers, so it can be installed first, while if it had a require it should get installed after and therefore would be able to override it.


/cc @danepowell

**Comment by danepowell** [comment]
Indeed, however it looks like @roygoldman is using an older version of Composer. You need to be on 1.9.0 to get the fix in #8085 that allows plugins to be consistently ordered by dependencies.

**Comment by roygoldman** [comment]
No, a dependency in `composer/installers` didn't fix this issue. I tested that prior to reporting the bug. here is the branch of the project with the dependency. 

https://github.com/roygoldman/composer-installers-discovery/tree/fix-installer-order

This is an issue as the result of the sorting which was added in the referenced commit. The sort logic, first sorts the packages in the order they need to be installed, such that `composer/installers` comes before `roygoldman/composer-installers-discovery`. It then [reverses the order](https://github.com/composer/composer/blob/master/src/Composer/Plugin/PluginManager.php#L258) which results in `roygoldman/composer-installers-discovery`'s Installer getting added to the list before the one provided by `composer/installers`. These are then checked in a "last loaded" order which results in the `composer/installers` version being used before mine. 

In versions of composer prior to 1.9.0, I was able to get this to work based on the package sorting order (using `sort-package: false` in the `composer.json`). However since the new sorting feature was added, i can no longer work around this with the latest version of composer.

I have tested this using composer 1.9.0 as well. Here is the info from another system where the issue is present. I believe I ran this on the wrong box initially.
```
Checking platform settings: OK              
Checking git settings: OK                   
Checking http connectivity to packagist: OK 
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK          ### 
Checking disk free space: OK                
Composer version: 1.9.0                     
PHP version: 7.3.8                          
PHP binary path: /usr/bin/php               
```

**Comment by danepowell** [comment]
That explanation doesn't really match with my understanding of the dependency resolver and plugin loader. Granted, I find the whole dependency resolver and plugin loader a bit arcane and I could be wrong, but here's what I understand.

I explain here why that array_reverse exists, and I don't think it does what you say: https://github.com/composer/composer/pull/8085#issuecomment-490930966

In fact, that array_reverse _should_ (if I understand the guts of all this correctly) be placing composer-installers at the top of the list, so it gets loaded first.

Intuition also points to this being the case because if what you describe is true and composer installers was getting loaded last, that would re-trigger #8065 in an even more widespread way than before. But I can tell you that #8065 is solidly closed in 1.9.0.

**Comment by roygoldman** [comment]
I am unfamiliar with #8065, so I can't tell you if that issue is related to this one. But I can tell you that the changed made to close #8065, in particular the logic mentioned, resulted in the issues I am experiencing. I put plenty of work into tracking down why the issue exists before filing this issue.

I have published project that demonstrates the issue, so you can reproduce it for yourself. It's available at https://github.com/roygoldman/composer-issue-8320.

There is an important factor to note about the way packages are getting loaded, which may be relevant here, but hasn't been touched on by either @danepowell or @Seldaek. That is the fact that, for some reason I haven;t tracked down yet, the plugins get loaded in batches, and not all at once. For example, in the above project, the installers get loaded in 3 batches. First, the composer level installers get loaded:

```
Composer\Installer\LibraryInstaller
Composer\Installer\PearInstaller
Composer\Installer\PluginInstaller
Composer\Installer\MetapackageInstaller
Composer\Installer\LibraryInstaller
Composer\Installer\PearInstaller
Composer\Installer\PluginInstaller
Composer\Installer\MetapackageInstaller
``
Then my installer:
```
RoyGoldman\ComposerInstallersDiscovery\Installer
```
Finally, the `composer/installers` one:
```
Composer\Installers\Installer
```

This means, that the dependency tree isn't fully being build to determine the plugin order in the first place. Using a composer version 1.8.6, these packages get loaded in two groups, the first is the same, while the second loads my installer AFTER the one provided by `composer/installers`.
```
Composer\Installers\Installer
RoyGoldman\ComposerInstallersDiscovery\Installer
```

The following is the full output of the commands listed in the project's README for using `1.9.0`.

```
rich@debian ~/composer-8320 (master) $ ./run.sh
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.9.0
PHP version: 7.3.6
PHP binary path: /usr/bin/php7.3
drupal/webform(type:drupal-module managed by Composer\Installers\Installer) is installed at /home/rich/tmp/composer-8320/modules/webform
roygoldman/composer-installers-discovery  dev-fix-installer-order  requires  composer/installers (^1.2)
roygoldman/drupal-project-installers      8.0.1                    requires  composer/installers (^1.2)
```

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/8723

**Comment by roygoldman** [comment]
@Seldaek, please reopen this.

[As stated](https://github.com/composer/composer/pull/8723#issuecomment-607875495) in #8723:

> My issue ... is focused more on the plugin loading order, and reordering the packages likely wouldn't solve those issues.

The merge in #8723 doesn't address the plugin loading order, simply package sorting, which since plugins are loaded in the reverse order, this isn't is still not resolved, and was falsely closed.

I will try and find time soon to re factor and rerun the above tests to verify this issue is in dependent.

Thanks!!

**Comment by Seldaek** [comment]
Ok sorry about that. Definitely would like to make sure this is solid before we release 2.0 :)

**Comment by Seldaek** [comment]
@roygoldman any chance to get an update here?

**Comment by Seldaek** [comment]
I tried installing roygoldman/composer-installers-discovery and tried things out and yeah I see what you mean, I think the array_reverse was added earlier because the sorting algo was wrong, but now it's not needed anymore and indeed does the opposite of what we want. So I removed it. Closing this now.
