### ISSUE TITLE
Unable to install package, insufficienterror mesaage

### ISSUE THREAD

**Issue by TerrePorter** [composer/composer#8728]
Originally posted on the package repo issues at https://github.com/bamarni/composer-bin-plugin/issues/51#issue-592196124

My `composer.json`:

```json
There isn't one, it's a empty directory.
```

Output of `composer diagnose`:

```
p$ composer diagnose
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.1
PHP version: 7.4.1
PHP binary path: /usr/bin/php7.4
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

When I run this command:

```
$ composer require --dev bamarni/composer-bin-plugin -vvv
```

I get the following output:

```
$ composer require --dev bamarni/composer-bin-plugin -vvv
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Loading config file /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/auth.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/vagrant/.composer): git branch --no-color --no-abbrev -v
Executing command (/home/vagrant/.composer): git describe --exact-match --tags
Executing command (/home/vagrant/.composer): git log --pretty="%H" -n1 HEAD
Executing command (/home/vagrant/.composer): hg branch
Executing command (/home/vagrant/.composer): fossil branch list
Executing command (/home/vagrant/.composer): fossil tag list
Executing command (/home/vagrant/.composer): svn info --xml
Reading /home/vagrant/.composer/vendor/composer/installed.json
Loading plugin Hirak\Prestissimo\Plugin
Downloading https://repo.packagist.org/packages.json
Writing /home/vagrant/.composer/cache/repo/https---repo.packagist.org/packages.json into cache
    1/1:        http://repo.packagist.org/p/provider-latest$855d97f1787e608a2c01eaa6a60891f2e00206983e8db3d5770517ddecea8ad4.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Running 1.10.1 (2020-03-13 20:34:27) with PHP 7.4.1 on Linux / 4.15.0-74-generic
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Loading config file /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/auth.json
Executing command (/home/vagrant/.composer): git branch --no-color --no-abbrev -v
Executing command (/home/vagrant/.composer): git describe --exact-match --tags
Executing command (/home/vagrant/.composer): git log --pretty="%H" -n1 HEAD
Executing command (/home/vagrant/.composer): hg branch
Executing command (/home/vagrant/.composer): fossil branch list
Executing command (/home/vagrant/.composer): fossil tag list
Executing command (/home/vagrant/.composer): svn info --xml
Reading /home/vagrant/.composer/vendor/composer/installed.json
Loading plugin Hirak\Prestissimo\Plugin_composer_tmp0
Downloading https://repo.packagist.org/packages.json
Writing /home/vagrant/.composer/cache/repo/https---repo.packagist.org/packages.json into cache
    1/1:        http://repo.packagist.org/p/provider-latest$855d97f1787e608a2c01eaa6a60891f2e00206983e8db3d5770517ddecea8ad4.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Reading ./composer.json
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Loading config file ./composer.json
Executing command (/home/vagrant/Code/_play/ttttmp): git branch --no-color --no-abbrev -v
Executing command (/home/vagrant/Code/_play/ttttmp): git describe --exact-match --tags
Executing command (/home/vagrant/Code/_play/ttttmp): git log --pretty="%H" -n1 HEAD
Executing command (/home/vagrant/Code/_play/ttttmp): hg branch
Executing command (/home/vagrant/Code/_play/ttttmp): fossil branch list
Executing command (/home/vagrant/Code/_play/ttttmp): fossil tag list
Executing command (/home/vagrant/Code/_play/ttttmp): svn info --xml
Reading /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Loading config file /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/vendor/composer/installed.json
Loading plugin Hirak\Prestissimo\Plugin_composer_tmp1
Downloading https://repo.packagist.org/packages.json
Writing /home/vagrant/.composer/cache/repo/https---repo.packagist.org/packages.json into cache
    1/1:        http://repo.packagist.org/p/provider-latest$855d97f1787e608a2c01eaa6a60891f2e00206983e8db3d5770517ddecea8ad4.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Writing /home/vagrant/.composer/cache/repo/https---repo.packagist.org/packages.json into cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2013.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2014.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2015.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2016.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2017.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2018.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2019.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2019-07.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2019-10.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2020-01.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-archived.json from cache
Writing /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-latest.json into cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/provider-bamarni$composer-bin-plugin.json from cache
Using version ^1.3 for bamarni/composer-bin-plugin
./composer.json has been created
Reading ./composer.json
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Loading config file ./composer.json
Executing command (/home/vagrant/Code/_play/ttttmp): git branch --no-color --no-abbrev -v
Executing command (/home/vagrant/Code/_play/ttttmp): git describe --exact-match --tags
Executing command (/home/vagrant/Code/_play/ttttmp): git log --pretty="%H" -n1 HEAD
Executing command (/home/vagrant/Code/_play/ttttmp): hg branch
Executing command (/home/vagrant/Code/_play/ttttmp): fossil branch list
Executing command (/home/vagrant/Code/_play/ttttmp): fossil tag list
Executing command (/home/vagrant/Code/_play/ttttmp): svn info --xml
Reading /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Loading config file /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/vendor/composer/installed.json
Loading plugin Hirak\Prestissimo\Plugin_composer_tmp2
Downloading https://repo.packagist.org/packages.json
Writing /home/vagrant/.composer/cache/repo/https---repo.packagist.org/packages.json into cache
Loading composer repositories with package information
Writing /home/vagrant/.composer/cache/repo/https---repo.packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2013.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2014.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2015.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2016.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2017.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2018.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2019.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2019-07.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2019-10.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-2020-01.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-archived.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/p-provider-latest.json from cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/provider-bamarni$composer-bin-plugin.json from cache
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.001 seconds
Analyzed 82 packages to resolve dependencies
Analyzed 78 rules to resolve dependencies
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Package operations: 1 install, 0 updates, 0 removals
Installs: bamarni/composer-bin-plugin:v1.3.0
  - Installing bamarni/composer-bin-plugin (v1.3.0): Reading /home/vagrant/.composer/cache/files/bamarni/composer-bin-plugin/8a7cd34f4251920cc9aa9f97728dbee1d410c361.zip from cache
Loading from cache
 Extracting archiveExecuting command (CWD): unzip -qq  '/home/vagrant/Code/_play/ttttmp/vendor/bamarni/composer-bin-plugin/01e360905eaa45df6fc37314d2a1b5b7' -d '/home/vagrant/Code/_play/ttttmp/vendor/composer/4f9e1104'
Plugin installation failed, rolling back
  - Removing bamarni/composer-bin-plugin (v1.3.0)

Installation failed, deleting ./composer.json.


  [ErrorException]
  include(/home/vagrant/Code/_play/ttttmp/vendor/bamarni/composer-bin-plugin/src/Plugin.php): failed to open stream: No such file or directory


Exception trace:
 () at phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:444
 Composer\Util\ErrorHandler::handle() at phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:444
 include() at phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:444
 Composer\Autoload\includeFile() at phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php:322
 Composer\Autoload\ClassLoader->loadClass() at n/a:n/a
 spl_autoload_call() at n/a:n/a
 class_exists() at phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php:204
 Composer\Plugin\PluginManager->registerPackage() at phar:///usr/local/bin/composer/src/Composer/Installer/PluginInstaller.php:62
 Composer\Installer\PluginInstaller->install() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:173
 Composer\Installer\InstallationManager->install() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:160
 Composer\Installer\InstallationManager->execute() at phar:///usr/local/bin/composer/src/Composer/Installer.php:611
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:232
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:248
 Composer\Command\RequireCommand->doUpdate() at phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:205
 Composer\Command\RequireCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:281
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:113
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:61
 require() at /usr/local/bin/composer:24

require [--dev] [--prefer-source] [--prefer-dist] [--fixed] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
```

And I expected this to happen:
It to install the package or at least tell me more about why it didn't install.

**Comment by TerrePorter** [comment]
any ideas? having this problem with on a completely new machine and a different package.

**Comment by Seldaek** [comment]
Can you try again after a `composer self-update --snapshot`? Although that might fail due to the plugin version, in which case you can setup composer from a git clone of this repo using the 1.10 branch and run it from bin/composer, or use --ignore-platform-reqs to force the require command to go through. I added some output in https://github.com/composer/composer/commit/96c1ba279aaaef5ce797e99de55db8c31c3cb26d so you should at least see what is going on.

**Comment by TerrePorter** [comment]
@Seldaek It installs without any problems with the snapshot version.

```
$ composer require --dev bamarni/composer-bin-plugin -vvv --ignore-platform-reqs
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Loading config file /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/auth.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/vagrant/.composer): git branch --no-color --no-abbrev -v
Executing command (/home/vagrant/.composer): git describe --exact-match --tags
Executing command (/home/vagrant/.composer): git log --pretty="%H" -n1 HEAD
Executing command (/home/vagrant/.composer): hg branch
Executing command (/home/vagrant/.composer): fossil branch list
Executing command (/home/vagrant/.composer): fossil tag list
Executing command (/home/vagrant/.composer): svn info --xml
Reading /home/vagrant/.composer/vendor/composer/installed.json
The "symfony/thanks" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "slince/composer-registry-manager" plugin was skipped because it requires a Plugin API version ("^1.1") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "composer/installers" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Running 2.0-dev+28d26bd3a4a70a2bcf1f42b95a9b3cabda711c53 (2020-04-09 12:02:33) with PHP 7.4.4 on Linux / 4.15.0-91-generic
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Loading config file /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/auth.json
Executing command (/home/vagrant/.composer): git branch --no-color --no-abbrev -v
Executing command (/home/vagrant/.composer): git describe --exact-match --tags
Executing command (/home/vagrant/.composer): git log --pretty="%H" -n1 HEAD
Executing command (/home/vagrant/.composer): hg branch
Executing command (/home/vagrant/.composer): fossil branch list
Executing command (/home/vagrant/.composer): fossil tag list
Executing command (/home/vagrant/.composer): svn info --xml
Reading /home/vagrant/.composer/vendor/composer/installed.json
The "symfony/thanks" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "slince/composer-registry-manager" plugin was skipped because it requires a Plugin API version ("^1.1") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "composer/installers" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Reading ./composer.json
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Loading config file ./composer.json
Executing command (/home/vagrant/Code/_play/composer_tests): git branch --no-color --no-abbrev -v
Executing command (/home/vagrant/Code/_play/composer_tests): git describe --exact-match --tags
Executing command (/home/vagrant/Code/_play/composer_tests): git log --pretty="%H" -n1 HEAD
Executing command (/home/vagrant/Code/_play/composer_tests): hg branch
Executing command (/home/vagrant/Code/_play/composer_tests): fossil branch list
Executing command (/home/vagrant/Code/_play/composer_tests): fossil tag list
Executing command (/home/vagrant/Code/_play/composer_tests): svn info --xml
Reading /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Loading config file /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/vendor/composer/installed.json
The "symfony/thanks" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "slince/composer-registry-manager" plugin was skipped because it requires a Plugin API version ("^1.1") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "composer/installers" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Downloading https://repo.packagist.org/packages.json
[200] https://repo.packagist.org/packages.json
Writing /home/vagrant/.composer/cache/repo/https---repo.packagist.org/packages.json into cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/provider-bamarni~composer-bin-plugin.json from cache
Downloading https://repo.packagist.org/p2/bamarni/composer-bin-plugin.json if modified
[304] https://repo.packagist.org/p2/bamarni/composer-bin-plugin.json
Using version ^1.3 for bamarni/composer-bin-plugin
./composer.json has been created
Reading ./composer.json
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Loading config file ./composer.json
Executing command (/home/vagrant/Code/_play/composer_tests): git branch --no-color --no-abbrev -v
Executing command (/home/vagrant/Code/_play/composer_tests): git describe --exact-match --tags
Executing command (/home/vagrant/Code/_play/composer_tests): git log --pretty="%H" -n1 HEAD
Executing command (/home/vagrant/Code/_play/composer_tests): hg branch
Executing command (/home/vagrant/Code/_play/composer_tests): fossil branch list
Executing command (/home/vagrant/Code/_play/composer_tests): fossil tag list
Executing command (/home/vagrant/Code/_play/composer_tests): svn info --xml
Reading /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Loading config file /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/vendor/composer/installed.json
The "symfony/thanks" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "slince/composer-registry-manager" plugin was skipped because it requires a Plugin API version ("^1.1") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "composer/installers" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Loading composer repositories with package information
Updating dependencies
Downloading https://repo.packagist.org/packages.json
[200] https://repo.packagist.org/packages.json
Writing /home/vagrant/.composer/cache/repo/https---repo.packagist.org/packages.json into cache
Reading /home/vagrant/.composer/cache/repo/https---repo.packagist.org/provider-bamarni~composer-bin-plugin.json from cache
Downloading https://repo.packagist.org/p2/bamarni/composer-bin-plugin.json if modified
[304] https://repo.packagist.org/p2/bamarni/composer-bin-plugin.json
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Analyzed 85 packages to resolve dependencies
Analyzed 85 rules to resolve dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Lock file operations: 1 install, 0 updates, 0 removals
Installs: bamarni/composer-bin-plugin:v1.3.0
  - Locking bamarni/composer-bin-plugin (v1.3.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Reading ./composer.lock
Package operations: 1 install, 0 updates, 0 removals
Installs: bamarni/composer-bin-plugin:v1.3.0
Reading /home/vagrant/.composer/cache/files/bamarni/composer-bin-plugin/8a7cd34f4251920cc9aa9f97728dbee1d410c361.zip from cache
  - Loading bamarni/composer-bin-plugin (v1.3.0) from cache
  - Installing bamarni/composer-bin-plugin (v1.3.0): Extracting archive
Executing command (CWD): unzip -qq  '/home/vagrant/Code/_play/composer_tests/vendor/composer/2c5e3eabdbacfabab750517d47d3e226' -d '/home/vagrant/Code/_play/composer_tests/vendor/composer/9900ed77'
The "bamarni/composer-bin-plugin" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Generating autoload files
```
It says it was skipped but I see the package in the vendor directory.

The error message might not be in the right place as it is just repeating the existing error. I think it has something to do with the extraction process but that seems to have been fixed in the latest snapshot. I tried to trace it down before work, but ran out of time. 

```

Installs: bamarni/composer-bin-plugin:v1.3.0
  - Installing bamarni/composer-bin-plugin (v1.3.0): Reading /home/vagrant/.composer/cache/files/bamarni/composer-bin-plugin/8a7cd34f4251920cc9aa9f97728dbee1d410c361.zip from cache
Loading from cache
 Extracting archiveExecuting command (CWD): unzip -qq  '/home/vagrant/Code/_play/composer_tests/vendor/bamarni/composer-bin-plugin/628ba104b6d1df59aa31d7b0500c44cb' -d '/home/vagrant/Code/_play/composer_tests/vendor/composer/2af30dcc'
Plugin installation failed (include(/home/vagrant/Code/_play/composer_tests/vendor/bamarni/composer-bin-plugin/src/Plugin.php): failed to open stream: No such file or directory), rolling back
  - Removing bamarni/composer-bin-plugin (v1.3.0)

Installation failed, deleting ./composer.json.


  [ErrorException]
  include(/home/vagrant/Code/_play/composer_tests/vendor/bamarni/composer-bin-plugin/src/Plugin.php): failed to open stream: No such file or directory
```

**Comment by Seldaek** [comment]
It might also be related to plugins.. If you can try again with latest stable (composer self-update --stable) I just released 1.10.2 which includes that commit about error reporting.. If you can still repro it maybe it'll help, and then try with --no-plugins if that fixes it then most likely it's not a composer issue but rather a plugin messing with it.

**Comment by TerrePorter** [comment]
Sorry been a busy couple of days. It failed with the version 1.10.5, but did work with the --no-plugins

**Comment by Seldaek** [comment]
Ok yeah obviously with --no-plugins it works as it doesn't load the plugin, which seems to be where it's failing. That was dumb from my part sorry. I wanted to know if it works without the other plugins, as I saw above that you have more plugins installed..

```
The "symfony/thanks" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "slince/composer-registry-manager" plugin was skipped because it requires a Plugin API version ("^1.1") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "composer/installers" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
```

Anyway, with 1.10.5, do you get more details next to the "Plugin installation failed" ?

**Comment by Houbsi** [comment]
+1 i have this issue still with 1.10.5 :( 

anything you need from me?

**Comment by svenced** [comment]
Just leaving this here for anyone coming from the search engines...This message popped up after upgrading to composer 2 form me... Easy fix, remove the plugin globally. Reference their announcement here: https://github.com/hirak/prestissimo#announcement-composer-2-is-now-available
