### ISSUE TITLE
Problem with extensions loaded

### ISSUE THREAD

**Issue by it-can** [composer/composer#8828]
Getting errors since PR https://github.com/composer/composer/pull/8812

```
Composer detected issues in your platform:
Your Composer dependencies require the following PHP extensions to be installed: imap, intl, pcntl
```

I use Laravel Horizon which is producing these errors I think... Their composer.json is here https://github.com/laravel/horizon/blob/4.x/composer.json

And also this package composer.json file, https://github.com/ddeboer/imap/blob/master/composer.json

All of these extensions are installed... And composer works correct before this commit...

```
php -v
PHP 7.4.5 (cli) (built: Apr 14 2020 12:54:33) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies


php -m

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imagick
imap
intl
json
libxml
mbstring
mcrypt
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib
```

**Comment by it-can** [comment]
@nicolas-grekas can you check this bug?

**Comment by nicolas-grekas** [comment]
I cannot sorry - maybe the CLI is running a different php runtime than the web/fpm server? I'd invite you to debug why the checks fail to find these extensions.

**Comment by it-can** [comment]
1 version installed of php...

**Comment by stof** [comment]
@it-can even with a single installed version, you can have separate php.ini files for the CLI and PHP-FPM.

**Comment by it-can** [comment]
No not the case...

**Comment by Seldaek** [comment]
Maybe we should allow pcntl to be missing in web SAPIs, or even always to keep the checks simple?

That said, the error indicates that `imap, intl, pcntl` are all missing, so it's not just about pcntl.

**Comment by it-can** [comment]
I’ll try to debug a little more tonight...

**Comment by it-can** [comment]
> Maybe we should allow pcntl to be missing in web SAPIs, or even always to keep the checks simple?
> 
> That said, the error indicates that `imap, intl, pcntl` are all missing, so it's not just about pcntl.

The ```imap, intl``` were errors on my local machine I see now. My server only nags about ```pcntl``` because this is not available in fpm...

**Comment by Seldaek** [comment]
Ok that's great to hear. Then we only have to fix pcntl one way or another on our end.

**Comment by Seldaek** [comment]
Alright you can self-update to latest and it should be fixed after a `composer dump-autoload`

**Comment by it-can** [comment]
> Alright you can self-update to latest and it should be fixed after a `composer dump-autoload`

Ok will try and let you know

**Comment by it-can** [comment]
Ok also seem to know why imap and intl are complaining. I use Deployer for my project to deploy and it sometimes uses the standard Mac os x PHP version, it needs to use my homebrew php version... Thanks for the help

**Comment by nayomnik** [comment]
In my case I had got a public host. Thus I could only upload folders. So what I ve done on localhost was :
1.  type in terminal 'composer install' and then   'composer update  -vvv' and get vendor updated
2. replace hosted vendor folder with new one

**Comment by yoeriboven** [comment]
This issue still exists in version 2.0.2.

The issue only shows up in [Tinkerwell](https://tinkerwell.app).

```
Composer detected issues in your platform:

Your Composer dependencies require the following PHP extensions to be installed: pcntl
```

**Comment by dkarlovi** [comment]
Not sure if this is the same issue, seems so.

I'm getting
```
Composer detected issues in your platform: Your Composer dependencies require the following PHP extensions to be installed: phar, xmlwriter
```

Both extensions are required by PHPUnit which is in `require-dev`. Doesn't make sense to add the modules to my Docker image (which is setup for prod) just to be able to use it with in dev. It seems the extensions required just by `require` should be required.

**Comment by Seldaek** [comment]
@dkarlovi if you `composer install --no-dev` then only stuff from require will be part of platform check. Otherwise your dev env should have everything to satisfy the dev requirements IMO.

**Comment by dkarlovi** [comment]
@Seldaek This is likely a special case, I have a build process which prepares the FPM Docker image and in dev I want to keep it close to what it's on prod, ideally identical. PHPUnit doesn't get run in there, I use a different image for that (which has those included).

So in this use case PHPUnit is blocking my FPM web app from working even though it should perfectly. I got around it by just specifying `--ignore-platform-req=ext-phar` even though it's there when installing, so it's not a blocker, thanks.

**Comment by Seldaek** [comment]
Ok yeah that's fine to ignore that one or even turn off the platform check on your local docker image if needed.. As long as you know what you are doing and running proper checks before deploying.

**Comment by dkarlovi** [comment]
Yeah, the image is built without these, of course. One consideration might be to add some sort of flag to skip platform check (at least for require-dev) since it's not exactly the same use case as platform req, latter still being useful in this case.

**Comment by Seldaek** [comment]
We do have the [platform-check](https://getcomposer.org/doc/06-config.md#platform-check) config option that you can set to false then the whole thing is gone. Can set that in your global config in the dev env for example.

**Comment by dkarlovi** [comment]
@Seldaek I've missed that, I guess I can do it globally on my workstation so I never get it in dev, but it's still there in prod.

Thanks!

**Comment by qazihamayun** [comment]
> We do have the [platform-check](https://getcomposer.org/doc/06-config.md#platform-check) config option that you can set to false then the whole thing is gone. Can set that in your global config in the dev env for example with `composer config -g platform-check false`.

This worked for me...

**Comment by dkarlovi** [comment]
Same here. Did it globally on my workstation, but Dockerfiles still do it without. 👍

**Comment by foremtehan** [comment]
The issue still exist 

I'm on windows machine and cannot install these extension locally:

```
Composer detected issues in your platform:

Your Composer dependencies require the following PHP extensions to be installed: pcntl, swoole
```

**Comment by dkarlovi** [comment]
@Seldaek is it possible to pass `platform-check false` one-time via the command line, not by changing the config?

**Comment by Seldaek** [comment]
@dkarlovi Using `--ignore-platform-reqs` on install/update/dump-autoload will skip generating the platform check.

@foremtehan If the extensions are required, it means the code isn't going to be running on windows. Or the requirements shouldn't be there if they are optional IMO.
