### ISSUE TITLE
Composer install fails for yii2

### ISSUE THREAD

**Issue by pcktuts** [composer/composer#9007]
My `composer.json`:

```json
{
    "name": "yiisoft/yii2-app-basic",
    "description": "Yii 2 Basic Project Template",
    "keywords": ["yii2", "framework", "basic", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.6.0",
        "yiisoft/yii2": "~2.0.14",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0 || ~2.1.0"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.1.0",
        "yiisoft/yii2-gii": "~2.1.0",
        "yiisoft/yii2-faker": "~2.0.0",
        "codeception/codeception": "^4.0",
        "codeception/verify": "~0.5.0 || ~1.1.0",
        "codeception/specify": "~0.4.6",
        "symfony/browser-kit": ">=2.7 <=4.2.4",
        "codeception/module-filesystem": "^1.0.0",
        "codeception/module-yii2": "^1.0.0",
        "codeception/module-asserts": "^1.0.0"
    },
    "config": {
        "process-timeout": 1800,
        "fxp-asset": {
            "enabled": false
        }
    },
    "scripts": {
        "post-install-cmd": [
            "yii\\composer\\Installer::postInstall"
        ],
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject",
            "yii\\composer\\Installer::postInstall"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ]
        },
        "yii\\composer\\Installer::postInstall": {
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}

```

Output of `composer diagnose`:

```
 % composer diagnose                 
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest stable version, run `composer self-update` to update (ae44a5963d18b61e0334295b005de7a4ee28aafc => 1.10.7)
Composer version: 2.0-dev+ae44a5963d18b61e0334295b005de7a4ee28aafc
PHP version: 7.4.7
PHP binary path: /usr/local/Cellar/php/7.4.7/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

When I run this command:

```
composer create-project --prefer-dist yiisoft/yii2-app-basic basic
```

I get the following output:

```
- Installing yiisoft/yii2-swiftmailer (2.1.2): Extracting archive
 60/73 [=======================>----]  82%    Failed to extract yiisoft/yii2-bootstrap: (9) unzip -qq  '/Users/krishnadas/Desktop/basic/vendor/composer/tmp-1bf8c09c11c2d6aafbed4889a6eb5a74' -d '/Users/krishnadas/Desktop/basic/vendor/composer/00e1daa6'

unzip:  cannot find or open /Users/krishnadas/Desktop/basic/vendor/composer/tmp-1bf8c09c11c2d6aafbed4889a6eb5a74.

    This most likely is due to a custom installer plugin not handling the returned Promise from the downloader
    See https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb for an example fix
    Failed to extract yiisoft/yii2-debug: (9) unzip -qq  '/Users/krishnadas/Desktop/basic/vendor/composer/tmp-e03660f58fb77541b4ce10c317d83dd1' -d '/Users/krishnadas/Desktop/basic/vendor/composer/51a99677'

unzip:  cannot find or open /Users/krishnadas/Desktop/basic/vendor/composer/tmp-e03660f58fb77541b4ce10c317d83dd1.

    This most likely is due to a custom installer plugin not handling the returned Promise from the downloader
    See https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb for an example fix
    Failed to extract yiisoft/yii2-faker: (9) unzip -qq  '/Users/krishnadas/Desktop/basic/vendor/composer/tmp-1c0bf34675bb8c3c7927aec3616c11a1' -d '/Users/krishnadas/Desktop/basic/vendor/composer/7d0a731e'

unzip:  cannot find or open /Users/krishnadas/Desktop/basic/vendor/composer/tmp-1c0bf34675bb8c3c7927aec3616c11a1.

    This most likely is due to a custom installer plugin not handling the returned Promise from the downloader
    See https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb for an example fix
 66/73 [=========================>--]  90%    Failed to extract yiisoft/yii2-gii: (9) unzip -qq  '/Users/krishnadas/Desktop/basic/vendor/composer/tmp-3a26e3df9911270ec8098dbe157f04fb' -d '/Users/krishnadas/Desktop/basic/vendor/composer/ef6ed8a2'

unzip:  cannot find or open /Users/krishnadas/Desktop/basic/vendor/composer/tmp-3a26e3df9911270ec8098dbe157f04fb.

    This most likely is due to a custom installer plugin not handling the returned Promise from the downloader
    See https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb for an example fix
 67/73 [=========================>--]  91%    Failed to extract yiisoft/yii2-swiftmailer: (9) unzip -qq  '/Users/krishnadas/Desktop/basic/vendor/composer/tmp-658c7de5814d4497ef4906f90a09d28a' -d '/Users/krishnadas/Desktop/basic/vendor/composer/de450073'

unzip:  cannot find or open /Users/krishnadas/Desktop/basic/vendor/composer/tmp-658c7de5814d4497ef4906f90a09d28a.

    This most likely is due to a custom installer plugin not handling the returned Promise from the downloader
    See https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb for an example fix
16 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
25 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> yii\composer\Installer::postCreateProject
chmod('runtime', 0777)...done.
chmod('web/assets', 0777)...done.
chmod('yii', 0755)...done.
> yii\composer\Installer::postInstall

```

And I expected this to happen:

Few of the packages were not getting installed so application not starting.

**Comment by Ayesh** [comment]
As the error message says:

> This most likely is due to a custom installer plugin not handling the returned Promise from the downloader
    See https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb for an example fix

I think the issue is in Yii composer installer plugin and not in Composer itself. I don't think Composer plugin for Yii is fully Composer 2 compatible yet.

**Comment by Seldaek** [comment]
ping @samdark

**Comment by samdark** [comment]
That's interesting. It worked well a few Composer 2 versions ago. Need to re-check it.

**Comment by Seldaek** [comment]
Yes it's https://github.com/composer/composer/pull/8952 which broke it, but see https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb as per the error message for a hint as to how this should be handled/fixed in custom installers.

**Comment by samdark** [comment]
That's weird but I cannot reproduce it with Composer version 2.0-dev (2.0-dev+ae44a5963d18b61e0334295b005de7a4ee28aafc) 2020-06-22 08:54:38.

```
composer clear-cache
composer create-project --prefer-dist yiisoft/yii2-app-basic basic
```

Creates a project and installs dependencies.

```
composer clear-cache
rm composer.lock
composer update
```

Updates dependencies.

**Comment by samdark** [comment]
Aha. Checked the pull request. It seems I have to be on OSX or Linux for it. Will re-check on a mac...

**Comment by samdark** [comment]
Reproduced.

**Comment by samdark** [comment]
@Seldaek I've tried prepared https://github.com/yiisoft/yii2-composer/pull/31 and it seems promises are resolved now. Still it does not fix the issue. Did I do anything wrong in that pull request?

**Comment by samdark** [comment]
He-he. Missing import :)

**Comment by samdark** [comment]
Tagged a release. Please try now.

**Comment by Seldaek** [comment]
PR looks good to me 👍  And if you're on windows you can try inside WSL, as long as unzip is installed there it'll also work.
